### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 474246820** [kelinZhou/PhotoSelector#4]
FATAL EXCEPTION: main
                                                                                                    Process: com.xianlan.ai, PID: 16094
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 
                                                                                                    Caused by: java.lang.NoSuchMethodException: com.kelin.okpermission.applicant.DefaultApplicant.<init> [class android.app.Activity, interface com.kelin.okpermission.router.PermissionRouter]
                                                                                                    	at java.lang.Class.getConstructor0(Class.java:2332)
                                                                                                    	at java.lang.Class.getConstructor(Class.java:1728)
                                                                                                    	at com.kelin.okpermission.OkPermission.createApplicantManager(OkPermission.kt:496)

**Comment by 474246820** [comment]
Caused by: java.lang.NoSuchMethodException: com.kelin.okpermission.applicant.DefaultApplicant.<init> [class android.app.Activity, interface com.kelin.okpermission.router.PermissionRouter]
                                                                                                    	at java.lang.Class.getConstructor0(Class.java:2332)
                                                                                                    	at java.lang.Class.getConstructor(Class.java:1728)
                                                                                                    	at com.kelin.okpermission.OkPermission.createApplicantManager(OkPermission.kt:496)
                                                                                                    	at com.kelin.okpermission.OkPermission.doOnApplyPermission(OkPermission.kt:454)
                                                                                                    	at com.kelin.okpermission.OkPermission.checkAndApply(OkPermission.kt:378)
                                                                                                    	at com.kelin.photoselector.callback.factory.PermissionCallbackFactory$createCallback$1.onAttach(PermissionCallbackFactory.kt:23)
                                                                                                    	at com.kelin.photoselector.callback.BaseCallback.createAndAttachTo(BaseCallback.kt:25)
                                                                                                    	at com.kelin.photoselector.PhotoSelector.attachCallback(PhotoSelector.kt:206)
                                                                                                    	at com.kelin.photoselector.PhotoSelector.realOpenSelector$photoselector_release(PhotoSelector.kt:452)

**Comment by kelinZhou** [comment]
请问你用的是哪个版本呢？
